### ISSUE TITLE
Capítulo de Análise Estática de Código Fonte

### ISSUE THREAD

**Issue by lucaskanashiro** [lucaskanashiro/tcc#1]
@paulormm terminei de escrever o capítulo 2 de Análise Estática de Código Fonte. Não sei se fiz do jeito que vc tinha pensado, por isso queria que vc desse uma lida pra eu ver o que eu posso melhorar até terça.

**Comment by paulormm** [comment]
Revisado! Correções e comentários feitos pessoalmente.
